### PR TITLE
Add an underscore prefix for unused variables

### PR DESCRIPTION
**Pull request by vjik**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Why should we do that, in principle if a variable is not used, we delete it?

**Comment by vjik** [comment]
> Why should we do that, in principle if a variable is not used, we delete it?
> 
> ```
> foreach ($items as $key => $_value) {
>     echo $key;
> }
> ```
> 
> ```
> foreach ($items as $key) {
>     echo $key;
> }
> ```
> 
> For that we use static analysis, otherwise it does not make sense.

Second code output values, not keys. We can't remove $value.

**Comment by terabytesoftw** [comment]
> > Why should we do that, in principle if a variable is not used, we delete it?
> > ```
> > foreach ($items as $key => $_value) {
> >     echo $key;
> > }
> > ```
> > 
> > 
> > ```
> > foreach ($items as $key) {
> >     echo $key;
> > }
> > ```
> > 
> > 
> > For that we use static analysis, otherwise it does not make sense.
> 
> Second code output values, not keys. We can't remove $value.



> > Why should we do that, in principle if a variable is not used, we delete it?
> > ```
> > foreach ($items as $key => $_value) {
> >     echo $key;
> > }
> > ```
> > 
> > 
> > ```
> > foreach ($items as $key) {
> >     echo $key;
> > }
> > ```
> > 
> > 
> > For that we use static analysis, otherwise it does not make sense.
> 
> Second code output values, not keys. We can't remove $value.

```php
foreach ($items as $key) {
     echo key($key);
}
```

**Comment by vjik** [comment]
> ```
> foreach (array_keys($items) as $key) {
>      echo $key;
> }
> ```
> 
> It can be solved in multiple ways, for me it is a bad idea to use `$_` ?

Usage `array_keys` reduces performance.

**Comment by terabytesoftw** [comment]
> > ```
> > foreach (array_keys($items) as $key) {
> >      echo $key;
> > }
> > ```
> > 
> > 
> > It can be solved in multiple ways, for me it is a bad idea to use `$_` ?
> 
> Usage `array_keys` reduces performance.

Having a variable that is not used and using `$_`, personally it is worse.

**Comment by samdark** [comment]
> Having a variable that is not used and using $_, personally it is worse.

It depends very much on what's being done. Generally, that's not that bad. It does not contradict PSR, it does play well with Psalm and you immediately see it as special thing.

**Review by samdark — APPROVED** [review]

**Pull request merged**
